export const GET_MYLIST = 'GET_MYLIST';
export const GET_RECOM = 'GET_RECOM';
export const ADD_SHOW_TO_MYLIST = 'ADD_SHOW_TO_MYLIST';
export const ADD_SHOW_TO_RECOM = 'ADD_SHOW_TO_RECOM';
export const REMOVE_SHOW_FROM_MYLIST = 'REMOVE_SHOW_FROM_MYLIST';
